[workspace]
package.license = "MIT OR Apache-2.0"
resolver = "3"
members = [
  "crates/takopack",
  "crates/takopack-core",
  "crates/takopack-python",
  "crates/takopack-rust",
]

[workspace.dependencies]
anyhow = { version = "1.0" }
cargo = { version = "0.97" }
cargo-util = { version = "0.2.30" }
cargo-util-schemas = { version = "0.14" }
cargo-util-terminal = { version = "0.1" }
clap = { version = "4.5" }
clap_mangen = { version = "0.2.29" }
dirs = { version = "5.0" }
env_logger = { version = "0.11" }
filetime = { version = "0.2" }
flate2 = { version = "1" }
futures = { version = "0.3" }
git2 = { version = ">= 0.19, < 0.21" }
glob = { version = "0.3" }
itertools = { version = "0.13" }
log = { version = "0.4" }
nu-ansi-term = { version = "0.50" }
regex = { version = "1.0" }
semver = { version = "1" }
serde = { version = "1" }
serde_derive = { version = "1" }
serde_json = { version = "1" }
serde_path_to_error = { version = "0.1.20" }
sha2 = { version = "0.10" }
takopack-core = { path = "crates/takopack-core" }
takopack-python = { path = "crates/takopack-python" }
takopack-rust = { path = "crates/takopack-rust" }
tar = { version = "0.4" }
tempfile = { version = "3" }
textwrap = { version = "0.16" }
toml = { version = "0.8" }
toml_edit = { version = "0.22" }
ureq = { version = "2" }
walkdir = { version = "2" }
