[package]
name = "takopack-python"
version = "0.2.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
flate2 = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
takopack-core = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
ureq = { workspace = true, default-features = true, features = ["tls"] }

clap = { workspace = true, optional = true }
serde_path_to_error = "0.1.20"

[features]
default = ["full"]
cli = ["dep:clap"]
full = ["cli", "render"]
render = []
