[package]
name = "takopack-python"
version = "0.2.0"
edition = "2024"
license.workspace = true

[dependencies]
flate2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
ureq = { workspace = true, default-features = true, features = ["tls"] }

# feature: cli
clap = { workspace = true, optional = true, features = ["derive"] }

# feature: render
regex = { workspace = true, optional = true }
takopack-core = { workspace = true, optional = true }
toml = { workspace = true, optional = true }

[features]
default = ["full"]
full = ["cli", "render"]

cli = ["dep:clap"]
render = ["dep:regex", "dep:takopack-core", "dep:toml"]
